defaults: &defaults
    docker:
      - image: cibuilds/hugo:latest
    # working_directory: ~/hugo
    # environment:
    #   HUGO_BUILD_DIR: ~/hugo/public
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      # install git
      - run: apk update && apk add git

      # checkout the repository
      - checkout

      # install git submodules for managing third-party dependencies
      - run: git submodule sync && git submodule update --init

      # build with Hugo
      - run: HUGO_ENV=production hugo -t meghna-hugo -v

      # - run:
      #     name: test our generated HTML files
      #     command: |
      #       htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
      #       --empty-alt-ignore --disable-external
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Test the commit for org or team processes"
          command: |
            git config --global user.email csmartin1024@gmail.com
            git config --global user.name Circle SeeEye
            git clone -b master --single-branch $CIRCLE_REPOSITORY_URL out
            cd out
            git checkout master || git checkout --orphan master
            git rm -rf .
            cd ..
            cp -a public/. out/.
            cd out
            git add -A
            git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
            git push origin master

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: source                